import Link from "next/link";
import { ProfileAvatar } from "@/components/client/profile-avatar";
import type { AdminClientDetail,AdminClientRecords } from "@/types/admin";
import type { ClientTab } from "@/domain/admin-client";
import { ClientProfileForm,ClientStatusAction } from "./client-profile-form";
import { adminDate,subscriptionLabel,ClientStatusBadge,ClientMetricCard,ClientTabs } from "./client-primitives";
import { ClientRecords } from "./client-records";
export function AdminClientHeader({item}:{item:AdminClientDetail}) {
  return <section className="crm-client-header"><ProfileAvatar account={{name:item.fullName||"Sem nome",avatarUrl:item.avatarUrl}} large/><div className="crm-client-identity"><p className="admin-overline">FICHA DO CLIENTE</p><h2>{item.fullName||"Cliente sem nome"}</h2><p>{item.email||"E-mail não informado"}</p><div className="crm-client-meta"><ClientStatusBadge status={item.status}/><span>Cadastro: {adminDate(item.createdAt)}</span><span>Plano: {item.planName||"Não definido"}</span></div>{item.avatarError?<small>Não foi possível carregar a foto privada.</small>:null}</div><Link className="button button-secondary" href={`/admin/clientes/${item.id}?aba=perfil`}>Editar perfil</Link></section>;
}
export function ClientOverview({item}:{item:AdminClientDetail}) {
  const weight=item.latestWeight?new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2}).format(item.latestWeight.value)+" kg":"Ainda não registrado";
  return <div><div className="crm-section-heading"><h3>Visão geral</h3><p>Resumo dos registros reais disponíveis para este cliente.</p></div><div className="crm-overview-grid"><ClientMetricCard label="Peso atual" value={weight} detail={item.latestWeight?adminDate(item.latestWeight.recordedAt):undefined}/><ClientMetricCard label="Último registro de evolução" value={adminDate(item.lastEvolutionAt)}/><ClientMetricCard label="Treino individual mais recente" value={item.currentWorkout||"Ainda não atribuído"}/><ClientMetricCard label="Plano alimentar individual mais recente" value={item.currentNutritionPlan||"Ainda não atribuído"}/><ClientMetricCard label="Última atividade registrada" value={adminDate(item.lastAccessAt)}/><ClientMetricCard label="Assinatura mais recente" value={subscriptionLabel(item.subscriptions[0]?.status)} detail={item.subscriptions[0]?.expiresAt?"Validade: "+adminDate(item.subscriptions[0].expiresAt):undefined}/></div><section className="crm-management"><h3>Status do cadastro</h3><p>Ativo/inativo representa o cadastro em clients. Não bloqueia o login Auth, não altera assinatura e não representa presença online.</p><ClientStatusAction id={item.id} status={item.status}/></section></div>;
}
export function AdminClientDetailView({item,tab,records}:{item:AdminClientDetail;tab:ClientTab;records:AdminClientRecords|null}) {
  return <div><Link className="admin-back" href="/admin/clientes">Voltar para clientes</Link><AdminClientHeader item={item}/><ClientTabs id={item.id} active={tab}/>{tab==="visao-geral"?<ClientOverview item={item}/>:tab==="perfil"?<div className="crm-profile-grid"><ClientProfileForm item={item}/><section className="crm-profile-info"><h3>Identidade e foto</h3><p>A foto real é exibida com URL assinada. O Admin não altera arquivos de avatar de terceiros.</p><dl><dt>ID do cliente</dt><dd>{item.id}</dd><dt>Cadastro</dt><dd>{adminDate(item.createdAt)}</dd><dt>Plano</dt><dd>{item.planName||"Não informado"}</dd><dt>Status</dt><dd><ClientStatusBadge status={item.status}/></dd></dl></section></div>:records?<ClientRecords data={records} id={item.id} tab={tab}/>:null}</div>;
}
