import Image from "next/image";
import Link from "next/link";
import { ExerciseActions } from "./exercise-actions";
import type { ExerciseFilters } from "@/domain/admin-exercise";
import type { AdminExercise } from "@/types/admin-exercise";

const value=(item:string|string[]|undefined)=>typeof item==="string"?item:"";
const pageUrl=(filters:ExerciseFilters,page:number)=>{const query=new URLSearchParams();for(const [key,item] of Object.entries(filters))if(typeof item==="string"&&key!=="page"&&item)query.set(key,item);query.set("page",String(page));return `/admin/exercicios?${query}`;};
const media=(item:AdminExercise)=>item.videoId&&item.thumbnailUrl?"Vídeo + foto":item.videoId?"Vídeo":item.thumbnailUrl?"Foto":"Sem mídia";

function ExerciseIdentity({item}:{item:AdminExercise}){return <div className="exercise-identity">{item.thumbnailUrl?<Image src={item.thumbnailUrl} alt="" width={52} height={52} unoptimized/>:<span className="exercise-thumbnail-placeholder" aria-label="Sem thumbnail"/>}<span><strong title={item.name}>{item.name}</strong><small>{item.scope==="CLIENT"?"Conteúdo do cliente":"Global"}</small></span></div>;}
function Status({active}:{active:boolean}){return <span className={`admin-status ${active?"active":"inactive"}`}>{active?"Ativo":"Inativo"}</span>;}

export function ExerciseLibrary({data,filters,categories}:{data:{items:AdminExercise[];total:number;page:number;pageSize:number};filters:ExerciseFilters;categories:{id:string;name:string}[]}){
 const pages=Math.max(1,Math.ceil(data.total/data.pageSize));
 return <><div className="crm-page-heading"><div><p className="admin-overline">BIBLIOTECA DE CONTEÚDO</p><h2>Exercícios</h2><p>Gerencie a base reutilizável de exercícios do ERLANY FIT.</p></div><Link className="button button-primary" href="/admin/exercicios/novo">+ Novo exercício</Link></div>
 <form className="crm-filters exercise-filters" method="get"><label className="crm-search">Buscar por nome<input name="q" defaultValue={value(filters.q)} placeholder="Nome do exercício"/></label><label>Categoria<select name="category" defaultValue={value(filters.category)||"all"}><option value="all">Todas</option>{categories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Nível<select name="level" defaultValue={value(filters.level)||"all"}><option value="all">Todos</option><option>Iniciante</option><option>Intermediário</option><option>Avançado</option></select></label><label>Equipamento<input name="equipment" defaultValue={value(filters.equipment)} placeholder="Ex.: Halteres"/></label><label>Status<select name="status" defaultValue={value(filters.status)||"all"}><option value="all">Todos</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select></label><div className="crm-filter-actions"><button className="button button-primary">Aplicar filtros</button><Link href="/admin/exercicios">Limpar filtros</Link></div></form>
<section className="crm-table-panel exercise-library-panel">{data.items.length?<><div className="admin-table-wrap exercise-desktop-table"><table className="crm-client-table exercise-table"><colgroup><col className="exercise-col-name"/><col className="exercise-col-category"/><col className="exercise-col-muscles"/><col className="exercise-col-equipment"/><col className="exercise-col-level"/><col className="exercise-col-status"/><col className="exercise-col-media"/><col className="exercise-col-actions"/></colgroup><thead><tr><th>Exercício</th><th>Categoria</th><th>Músculos</th><th>Equipamento</th><th>Nível</th><th>Status</th><th>Mídia</th><th>Ações</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td><ExerciseIdentity item={item}/></td><td title={item.category??undefined}>{item.category??"—"}</td><td title={item.muscles.join(", ")||undefined}>{item.muscles.join(", ")||"—"}</td><td title={item.equipment??undefined}>{item.equipment??"—"}</td><td><span className="exercise-level">{item.level??"—"}</span></td><td><Status active={item.isActive}/></td><td><span className="exercise-media" title={media(item)}>{media(item)}</span></td><td><ExerciseActions id={item.id} name={item.name} isActive={item.isActive}/></td></tr>)}</tbody></table></div><div className="exercise-mobile-list">{data.items.map(item=><article className="exercise-card" key={item.id}><header><ExerciseIdentity item={item}/><Status active={item.isActive}/></header><p className="exercise-card-category">{item.category??"Sem categoria"}{item.muscles.length?` · ${item.muscles.join(", ")}`:""}</p><dl><div><dt>Equipamento</dt><dd>{item.equipment??"Não informado"}</dd></div><div><dt>Nível</dt><dd><span className="exercise-level">{item.level??"—"}</span></dd></div><div><dt>Mídia</dt><dd>{media(item)}</dd></div></dl><ExerciseActions id={item.id} name={item.name} isActive={item.isActive}/></article>)}</div></>:<div className="crm-empty exercise-empty"><span aria-hidden="true">✦</span><strong>Nenhum exercício encontrado</strong><p>Crie um exercício ou ajuste os filtros para consultar a biblioteca.</p><Link className="button button-primary" href="/admin/exercicios/novo">Criar exercício</Link></div>}</section>
 <nav className="admin-pagination exercise-pagination" aria-label="Paginação de exercícios"><span>{data.total} registro(s) · Página {data.page} de {pages}</span>{data.page>1?<Link href={pageUrl(filters,data.page-1)}>Anterior</Link>:null}{data.page*data.pageSize<data.total?<Link href={pageUrl(filters,data.page+1)}>Próxima</Link>:null}</nav></>;
}
