"use client";
import Link from "next/link";
import { useActionState, useState } from "react";
import { saveNutritionPlan, type NutritionActionState } from "@/app/(admin)/admin/alimentacao/actions";
import type { AdminWorkoutClient } from "@/repositories/admin-workout-repository";

type Values = { name: string; description: string; objective: string; notes: string; scope: "GLOBAL" | "CLIENT"; clientId: string; isActive: boolean };
const valuesFor = (item?: Record<string, unknown>): Values => ({ name: String(item?.name ?? ""), description: String(item?.description ?? ""), objective: String(item?.objective ?? ""), notes: String(item?.notes ?? ""), scope: item?.scope === "CLIENT" ? "CLIENT" : "GLOBAL", clientId: String(item?.client_id ?? ""), isActive: item?.is_active !== false });
export function NutritionPlanEditor({ clients, item }: { clients: AdminWorkoutClient[]; item?: Record<string, unknown> }) {
  const [values, setValues] = useState(() => valuesFor(item)); const [state, action, pending] = useActionState(saveNutritionPlan.bind(null, item ? String(item.id) : null), {} as NutritionActionState);
  const update = <K extends keyof Values>(key: K, value: Values[K]) => setValues((current) => ({ ...current, [key]: value }));
  return <form action={action} className="crm-profile-form nutrition-editor"><header className="workout-editor-header"><div><p className="admin-overline">{item ? "EDITAR PLANO" : "NOVO PLANO"}</p><h2>{values.name || "Plano alimentar"}</h2><p>Defina o objetivo e o público antes de organizar refeições e distribuição.</p></div><div className="workout-editor-badges"><span className={`workout-status ${values.isActive ? "active" : "inactive"}`}>{values.isActive ? "● Ativo" : "● Inativo"}</span><span className="workout-status neutral">{values.scope === "GLOBAL" ? "Global" : "Cliente"}</span></div></header>{state.error ? <p className="crm-form-error" role="alert">{state.error}</p> : null}<label>Nome<input name="name" required minLength={2} maxLength={120} value={values.name} onChange={(event) => update("name", event.target.value)} /></label><label>Objetivo<input name="objective" maxLength={160} placeholder="Ex.: Redução de gordura" value={values.objective} onChange={(event) => update("objective", event.target.value)} /></label><label>Descrição<textarea name="description" maxLength={4000} value={values.description} onChange={(event) => update("description", event.target.value)} /></label><label>Orientações gerais<textarea name="notes" maxLength={4000} value={values.notes} onChange={(event) => update("notes", event.target.value)} /></label><label>Escopo<select name="scope" value={values.scope} onChange={(event) => update("scope", event.target.value === "CLIENT" ? "CLIENT" : "GLOBAL")}><option value="GLOBAL">Global</option><option value="CLIENT">Cliente</option></select></label><label>Cliente (somente CLIENT)<select name="clientId" disabled={values.scope !== "CLIENT"} required={values.scope === "CLIENT"} value={values.clientId} onChange={(event) => update("clientId", event.target.value)}><option value="">Selecione o cliente</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label className="crm-create-confirm"><input name="isActive" type="checkbox" checked={values.isActive} onChange={(event) => update("isActive", event.target.checked)} /> Plano ativo</label><footer className="workout-editor-actions"><Link href={item ? `/admin/alimentacao/${item.id}` : "/admin/alimentacao"} className="button button-outline">Cancelar</Link><button className="button button-primary" disabled={pending}>{pending ? "Salvando…" : "Salvar plano"}</button></footer></form>;
}
