"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { saveTip, type EditorialActionState } from "@/app/(admin)/admin/dicas/actions";
import type { AdminTip, EditorialClient } from "@/types/admin-editorial";
import { EditorialCover } from "./editorial-cover";

type Fields = { title: string; slug: string; summary: string; content: string; categoryId: string; scope: "GLOBAL" | "CLIENT"; clientId: string; isActive: boolean };
const initial = (item?: AdminTip): Fields => ({ title: item?.title ?? "", slug: item?.slug ?? "", summary: item?.summary ?? "", content: item?.content ?? "", categoryId: item?.categoryId ?? "", scope: item?.scope ?? "GLOBAL", clientId: item?.clientId ?? "", isActive: item?.isActive ?? true });

export function TipEditor({ item, clients, categories }: { item?: AdminTip; clients: EditorialClient[]; categories: { id: string; name: string }[] }) {
  const [values, setValues] = useState(() => initial(item)); const [state, action, pending] = useActionState(saveTip.bind(null, item?.id ?? null), {} as EditorialActionState);
  const update = <K extends keyof Fields>(key: K, value: Fields[K]) => setValues((current) => ({ ...current, [key]: value }));
  return <form action={action} className="crm-profile-form editorial-form" encType="multipart/form-data"><header className="workout-editor-header"><div><p className="admin-overline">DICAS DA ERLANY</p><h2>{item ? "Editar dica" : "Nova dica"}</h2><p>Publique conteúdo editorial global ou exclusivo para um cliente.</p></div><span className={`workout-status ${values.isActive ? "active" : "inactive"}`}>{values.isActive ? "● Ativa" : "● Inativa"}</span></header>{state.error ? <p className="crm-form-error" role="alert">{state.error}</p> : null}<label>Título<input name="title" required minLength={2} maxLength={160} value={values.title} onChange={(event) => update("title", event.target.value)} /></label><label>Slug<input name="slug" maxLength={180} value={values.slug} onChange={(event) => update("slug", event.target.value)} /><small>Usado para identificar o conteúdo. Se vazio, será gerado pelo título.</small></label><label>Categoria<select name="categoryId" value={values.categoryId} onChange={(event) => update("categoryId", event.target.value)}><option value="">Sem categoria</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Resumo<textarea name="summary" maxLength={500} value={values.summary} onChange={(event) => update("summary", event.target.value)} /></label><label>Conteúdo<textarea name="content" required maxLength={12000} value={values.content} onChange={(event) => update("content", event.target.value)} /></label><div className="workout-form-grid"><label>Escopo<select name="scope" value={values.scope} onChange={(event) => update("scope", event.target.value === "CLIENT" ? "CLIENT" : "GLOBAL")}><option value="GLOBAL">Global</option><option value="CLIENT">Cliente</option></select></label><label>Cliente<select name="clientId" disabled={values.scope !== "CLIENT"} required={values.scope === "CLIENT"} value={values.clientId} onChange={(event) => update("clientId", event.target.value)}><option value="">Selecione o cliente</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}{client.email ? ` · ${client.email}` : ""}</option>)}</select></label></div><EditorialCover imageUrl={item?.imageUrl} error={state.coverError} /><label className="workout-checkbox"><input name="isActive" type="checkbox" checked={values.isActive} onChange={(event) => update("isActive", event.target.checked)} /> Dica ativa</label><footer className="workout-editor-actions"><Link href="/admin/dicas" className="button button-outline">Cancelar</Link><button className="button button-primary" disabled={pending}>{pending ? "Salvando…" : "Salvar dica"}</button>{state.success ? <p className="crm-feedback" role="status">{state.success}</p> : null}</footer></form>;
}
