import type { SupabaseClient } from "@supabase/supabase-js";
import type { AdminWorkout,AssignmentInput,WorkoutExerciseInput,WorkoutInput } from "@/types/admin-workout";
type Row=Record<string,unknown>;
type ProfileRow={full_name?:unknown;email?:unknown;avatar_url?:unknown}|null;
type ClientRow={id:unknown;profile?:ProfileRow|ProfileRow[]};
export type AdminWorkoutClient={id:string;name:string;email:string|null;avatarUrl:string|null};
const scheduledWeekdays=(r:Row)=>[...new Set((Array.isArray(r.workout_assignments)?r.workout_assignments:[]).flatMap((assignment)=>{const row=assignment as Row;return (Array.isArray(row.schedule)?row.schedule:[]).flatMap((schedule)=>{const item=schedule as Row;return item.schedule_kind==="WORKOUT"&&Number.isInteger(item.weekday)&&Number(item.weekday)>=0&&Number(item.weekday)<=6?[Number(item.weekday)]:[];});}))].sort((left,right)=>left-right);
const map=(r:Row):AdminWorkout=>({id:String(r.id),name:String(r.name),description:r.description as string??null,category:r.category as string??null,level:r.level as string??null,durationMinutes:r.duration_minutes as number??null,scope:r.scope as AdminWorkout["scope"],clientId:r.client_id as string??null,status:r.status as AdminWorkout["status"],isActive:!!r.is_active,exerciseCount:Array.isArray(r.workout_exercises)?r.workout_exercises.length:0,scheduledWeekdays:scheduledWeekdays(r),createdAt:String(r.created_at),updatedAt:String(r.updated_at)});
const profileOf=(row:ClientRow)=>Array.isArray(row.profile)?row.profile[0]??null:row.profile??null;
const clientOption=(row:ClientRow):AdminWorkoutClient=>{const profile=profileOf(row);return {id:String(row.id),name:typeof profile?.full_name==="string"&&profile.full_name.trim()?profile.full_name.trim():"Cliente sem nome",email:typeof profile?.email==="string"?profile.email:null,avatarUrl:typeof profile?.avatar_url==="string"?profile.avatar_url:null};};
export function createAdminWorkoutRepository(client:SupabaseClient){return {
 async list(filters:{q?:string;status?:string;scope?:string;page?:string}={}){const page=Math.max(1,Number(filters.page)||1),size=20,start=(page-1)*size;let query=client.from("workouts").select("*,workout_exercises(id),workout_assignments(schedule:workout_assignment_schedule(weekday,schedule_kind))",{count:"exact"}).order("updated_at",{ascending:false});if(filters.q)query=query.ilike("name",`%${filters.q.slice(0,100)}%`);if(filters.status==="active"||filters.status==="inactive")query=query.eq("is_active",filters.status==="active");if(filters.scope==="GLOBAL"||filters.scope==="CLIENT")query=query.eq("scope",filters.scope);const {data,error,count}=await query.range(start,start+size-1);if(error)throw error;return {items:(data??[]).map(x=>map(x as Row)),total:count??0,page,pageSize:size};},
 async get(id:string){const {data,error}=await client.from("workouts").select("*,workout_exercises(id,exercise_id,position,sets,repetitions,load,rest_seconds,duration_seconds,notes,exercise:exercises(id,name,thumbnail_url,video_id))").eq("id",id).single();if(error)throw error;return data as Row;},
 async exercises(){const {data,error}=await client.from("exercises").select("id,name,level,thumbnail_asset:media_assets(bucket,path),video:videos(provider_video_id)").eq("is_active",true).order("name").limit(300);if(error)throw error;return data??[];},
 async clients(){const {data,error}=await client.from("clients").select("id,profile:profiles(full_name,email,avatar_url)").order("created_at").limit(300);if(error)throw error;return ((data??[]) as ClientRow[]).map(clientOption);},
 async save(id:string|null,input:WorkoutInput){if(id){const {data,error}=await client.from("workouts").update({name:input.name,description:input.description,category:input.category,level:input.level,duration_minutes:input.durationMinutes,scope:input.scope,client_id:input.clientId,status:input.status,is_active:input.isActive}).eq("id",id).select("id").single();if(error)throw error;return data.id as string;}const slug=`${input.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"treino"}-${crypto.randomUUID().slice(0,8)}`;const {data,error}=await client.from("workouts").insert({name:input.name,description:input.description,category:input.category,level:input.level,duration_minutes:input.durationMinutes,scope:input.scope,client_id:input.clientId,status:input.status,is_active:input.isActive,slug}).select("id").single();if(error)throw error;return data.id as string;},
 async toggle(id:string,isActive:boolean){const {data,error}=await client.from("workouts").update({is_active:isActive}).eq("id",id).select("is_active").single();if(error||data?.is_active!==isActive)throw error??new Error("Status não atualizado.");return data.is_active as boolean;},
 async addExercise(workoutId:string,input:WorkoutExerciseInput){const {count,error:countError}=await client.from("workout_exercises").select("id",{count:"exact",head:true}).eq("workout_id",workoutId);if(countError)throw countError;const {error}=await client.from("workout_exercises").insert({workout_id:workoutId,exercise_id:input.exerciseId,position:count??0,sets:input.sets,repetitions:input.repetitions,load:input.load,rest_seconds:input.restSeconds,duration_seconds:input.durationSeconds,notes:input.notes});if(error)throw error;},
 async removeExercise(id:string){const {error}=await client.from("workout_exercises").delete().eq("id",id);if(error)throw error;},
 async updateExercise(id:string,input:WorkoutExerciseInput){const {error}=await client.from("workout_exercises").update({sets:input.sets,repetitions:input.repetitions,load:input.load,rest_seconds:input.restSeconds,duration_seconds:input.durationSeconds,notes:input.notes}).eq("id",id);if(error)throw error;},
 async moveExercise(workoutId:string,id:string,direction:-1|1){const {data,error}=await client.from("workout_exercises").select("id,position").eq("workout_id",workoutId).order("position");if(error)throw error;const rows=data??[],index=rows.findIndex(row=>row.id===id),other=rows[index+direction];if(index<0||!other)return;const current=rows[index];const {error:first}=await client.from("workout_exercises").update({position:-1}).eq("id",current.id);if(first)throw first;const {error:second}=await client.from("workout_exercises").update({position:current.position}).eq("id",other.id);if(second)throw second;const {error:third}=await client.from("workout_exercises").update({position:other.position}).eq("id",current.id);if(third)throw third;},
 async assignments(workoutId:string){const {data,error}=await client.from("workout_assignments").select("*,client:clients(id,profile:profiles(full_name)),schedule:workout_assignment_schedule(id,weekday,schedule_kind)").eq("workout_id",workoutId).order("created_at",{ascending:false});if(error)throw error;return data??[];},
 async assign(workoutId:string,input:AssignmentInput){const {data,error}=await client.from("workout_assignments").insert({client_id:input.clientId,workout_id:workoutId,starts_on:input.startsOn,ends_on:input.endsOn,notes:input.notes}).select("id").single();if(error)throw error;if(input.days.length){const {error:scheduleError}=await client.from("workout_assignment_schedule").insert(input.days.map(day=>({assignment_id:data.id,weekday:day.weekday,schedule_kind:day.kind})));if(scheduleError)throw scheduleError;}return data.id as string;},
 async updateAssignment(id:string,input:AssignmentInput){const {error}=await client.from("workout_assignments").update({client_id:input.clientId,starts_on:input.startsOn,ends_on:input.endsOn,notes:input.notes}).eq("id",id);if(error)throw error;const {error:removeError}=await client.from("workout_assignment_schedule").delete().eq("assignment_id",id);if(removeError)throw removeError;if(input.days.length){const {error:scheduleError}=await client.from("workout_assignment_schedule").insert(input.days.map(day=>({assignment_id:id,weekday:day.weekday,schedule_kind:day.kind})));if(scheduleError)throw scheduleError;}},
 async toggleAssignment(id:string,isActive:boolean){const {error}=await client.from("workout_assignments").update({is_active:isActive}).eq("id",id);if(error)throw error;},
 async cancelAssignment(id:string){const {error}=await client.from("workout_assignments").delete().eq("id",id);if(error)throw error;}
};}
