import type { SupabaseClient } from "@supabase/supabase-js";
import type { AdminNutritionPlan, NutritionAssignmentInput, NutritionMealInput, NutritionPlanInput } from "@/types/admin-nutrition";
import type { AdminWorkoutClient } from "./admin-workout-repository";

type Row = Record<string, unknown>;
const profile = (value: unknown) => Array.isArray(value) ? value[0] as Row | undefined : value as Row | null;
const toClient = (row: Row): AdminWorkoutClient => { const item = profile(row.profile); return { id: String(row.id), name: typeof item?.full_name === "string" && item.full_name.trim() ? item.full_name : "Cliente sem nome", email: typeof item?.email === "string" ? item.email : null, avatarUrl: typeof item?.avatar_url === "string" ? item.avatar_url : null }; };
const mapPlan = (row: Row): AdminNutritionPlan => ({ id: String(row.id), name: String(row.name), description: row.description as string | null ?? null, objective: row.objective as string | null ?? null, notes: row.notes as string | null ?? null, scope: row.scope === "CLIENT" ? "CLIENT" : "GLOBAL", clientId: row.client_id as string | null ?? null, isActive: row.is_active !== false, mealCount: Array.isArray(row.nutrition_meals) ? row.nutrition_meals.length : 0, assignmentCount: Array.isArray(row.nutrition_assignments) ? row.nutrition_assignments.length : 0, updatedAt: String(row.updated_at) });

export function createAdminNutritionRepository(client: SupabaseClient) {
  const planScope = async (planId: string) => { const { data, error } = await client.from("nutrition_plans").select("scope,client_id").eq("id", planId).single(); if (error) throw error; return data as { scope: "GLOBAL" | "CLIENT"; client_id: string | null }; };
  const replaceItems = async (mealId: string, input: NutritionMealInput) => { const { error: removeError } = await client.from("nutrition_meal_items").delete().eq("nutrition_meal_id", mealId); if (removeError) throw removeError; const { error } = await client.from("nutrition_meal_items").insert(input.items.map((item) => ({ nutrition_meal_id: mealId, food_name: item.foodName, quantity: item.quantity, unit: item.unit, notes: item.notes, item_order: item.itemOrder }))); if (error) throw error; };
  const replaceSchedule = async (assignmentId: string, days: number[]) => { const { error: removeError } = await client.from("nutrition_assignment_schedule").delete().eq("assignment_id", assignmentId); if (removeError) throw removeError; const { error } = await client.from("nutrition_assignment_schedule").insert(days.map((weekday) => ({ assignment_id: assignmentId, weekday, is_available: true }))); if (error) throw error; };
  return {
    async list(filters: { q?: string; status?: string; scope?: string; page?: string } = {}) { const page = Math.max(1, Number(filters.page) || 1), pageSize = 20, start = (page - 1) * pageSize; let query = client.from("nutrition_plans").select("*,nutrition_meals(id),nutrition_assignments(id)", { count: "exact" }).order("updated_at", { ascending: false }); if (filters.q) query = query.ilike("name", `%${filters.q.slice(0, 100)}%`); if (filters.status === "active" || filters.status === "inactive") query = query.eq("is_active", filters.status === "active"); if (filters.scope === "GLOBAL" || filters.scope === "CLIENT") query = query.eq("scope", filters.scope); const { data, error, count } = await query.range(start, start + pageSize - 1); if (error) throw error; return { items: (data ?? []).map((row) => mapPlan(row as Row)), total: count ?? 0, page, pageSize }; },
    async get(id: string) { const { data, error } = await client.from("nutrition_plans").select("*,nutrition_meals(id,nutrition_plan_id,name,meal_time,meal_order,description,guidance,recipe_id,recipe:recipes(id,name),items:nutrition_meal_items(id,food_name,quantity,unit,notes,item_order)),nutrition_assignments(id,client_id,starts_on,ends_on,is_active,notes,client:clients(id,profile:profiles(full_name,email)),schedule:nutrition_assignment_schedule(id,weekday,is_available))").eq("id", id).single(); if (error) throw error; return data as Row; },
    async clients() { const { data, error } = await client.from("clients").select("id,profile:profiles(full_name,email,avatar_url)").order("created_at").limit(300); if (error) throw error; return (data ?? []).map((row) => toClient(row as Row)); },
    async recipes() { const { data, error } = await client.from("recipes").select("id,name").eq("is_active", true).order("name").limit(300); if (error) throw error; return data ?? []; },
    async save(id: string | null, input: NutritionPlanInput) { const payload = { name: input.name, description: input.description, objective: input.objective, notes: input.notes, scope: input.scope, client_id: input.clientId, is_active: input.isActive }; if (id) { const { data, error } = await client.from("nutrition_plans").update(payload).eq("id", id).select("id").single(); if (error) throw error; return data.id as string; } const { data, error } = await client.from("nutrition_plans").insert(payload).select("id").single(); if (error) throw error; return data.id as string; },
    async toggle(id: string, active: boolean) { const { data, error } = await client.from("nutrition_plans").update({ is_active: active }).eq("id", id).select("is_active").single(); if (error || data?.is_active !== active) throw error ?? new Error("Status não atualizado."); return data.is_active as boolean; },
    async saveMeal(planId: string, id: string | null, input: NutritionMealInput) { const scope = await planScope(planId); const payload = { nutrition_plan_id: planId, name: input.name, meal_time: input.mealTime, description: input.description, guidance: input.guidance, recipe_id: input.recipeId, scope: scope.scope, client_id: scope.client_id }; let mealId = id; if (mealId) { const { error } = await client.from("nutrition_meals").update(payload).eq("id", mealId).eq("nutrition_plan_id", planId); if (error) throw error; } else { const { count, error: countError } = await client.from("nutrition_meals").select("id", { count: "exact", head: true }).eq("nutrition_plan_id", planId); if (countError) throw countError; const { data, error } = await client.from("nutrition_meals").insert({ ...payload, meal_order: count ?? 0 }).select("id").single(); if (error) throw error; mealId = data.id as string; } await replaceItems(mealId, input); return mealId; },
    async removeMeal(planId: string, id: string) { const { error } = await client.from("nutrition_meals").delete().eq("id", id).eq("nutrition_plan_id", planId); if (error) throw error; },
    async assignments(planId: string) { const { data, error } = await client.from("nutrition_assignments").select("*,client:clients(id,profile:profiles(full_name,email)),schedule:nutrition_assignment_schedule(id,weekday,is_available)").eq("nutrition_plan_id", planId).order("created_at", { ascending: false }); if (error) throw error; return data ?? []; },
    async assign(planId: string, input: NutritionAssignmentInput) { const { data, error } = await client.from("nutrition_assignments").insert({ nutrition_plan_id: planId, client_id: input.clientId, starts_on: input.startsOn, ends_on: input.endsOn, notes: input.notes }).select("id").single(); if (error) throw error; await replaceSchedule(data.id as string, input.days); return data.id as string; },
    async updateAssignment(planId: string, id: string, input: NutritionAssignmentInput) { const { error } = await client.from("nutrition_assignments").update({ client_id: input.clientId, starts_on: input.startsOn, ends_on: input.endsOn, notes: input.notes }).eq("id", id).eq("nutrition_plan_id", planId); if (error) throw error; await replaceSchedule(id, input.days); },
    async toggleAssignment(id: string, active: boolean) { const { error } = await client.from("nutrition_assignments").update({ is_active: active }).eq("id", id); if (error) throw error; },
    async cancelAssignment(id: string) { const { error } = await client.from("nutrition_assignments").delete().eq("id", id); if (error) throw error; },
  };
}
