import type { SupabaseClient } from "@supabase/supabase-js";
import type { AdminRecipe, AdminRecipeIngredient, AdminTip, EditorialClient, RecipeInput, TipInput } from "@/types/admin-editorial";
import type { editorialFilters } from "@/domain/admin-editorial";
import { readAdminPage } from "./admin-page";

type Row = Record<string, unknown>;
const item = (value: unknown): Row | null => Array.isArray(value) ? value[0] as Row ?? null : value as Row | null;
const clientName = (row: Row) => { const profile = item(row.profile); return typeof profile?.full_name === "string" && profile.full_name.trim() ? profile.full_name : "Cliente sem nome"; };
const signed = async (client: SupabaseClient, asset: Row | null) => asset?.bucket && asset.path ? (await client.storage.from(String(asset.bucket)).createSignedUrl(String(asset.path), 900)).data?.signedUrl ?? null : null;
const tipSelect = "id,title,slug,summary,content,category_id,scope,client_id,is_active,image_asset_id,created_at,updated_at,category:tip_categories(id,name),client:clients(id,profile:profiles(full_name,email,avatar_url)),image_asset:media_assets(bucket,path)";
const recipeSelect = "id,name,slug,description,instructions,scope,client_id,is_active,image_asset_id,created_at,updated_at,client:clients(id,profile:profiles(full_name,email,avatar_url)),image_asset:media_assets(bucket,path),recipe_ingredients(id,name,quantity,unit,notes,ingredient_order)";

async function mapTip(row: Row, client: SupabaseClient): Promise<AdminTip> {
  const category = item(row.category); const owner = item(row.client); const image = item(row.image_asset);
  return { id: String(row.id), title: String(row.title), slug: String(row.slug), summary: row.summary as string | null ?? null, content: String(row.content), categoryId: row.category_id as string | null ?? null, categoryName: category?.name as string | null ?? null, scope: row.scope === "CLIENT" ? "CLIENT" : "GLOBAL", clientId: row.client_id as string | null ?? null, clientName: owner ? clientName(owner) : null, isActive: row.is_active !== false, imageAssetId: row.image_asset_id as string | null ?? null, imagePath: image?.path as string | null ?? null, imageUrl: await signed(client, image), createdAt: String(row.created_at), updatedAt: String(row.updated_at) };
}
async function mapRecipe(row: Row, client: SupabaseClient): Promise<AdminRecipe> {
  const owner = item(row.client); const image = item(row.image_asset); const ingredients = Array.isArray(row.recipe_ingredients) ? row.recipe_ingredients as Row[] : [];
  return { id: String(row.id), name: String(row.name), slug: String(row.slug), description: row.description as string | null ?? null, instructions: row.instructions as string | null ?? null, scope: row.scope === "CLIENT" ? "CLIENT" : "GLOBAL", clientId: row.client_id as string | null ?? null, clientName: owner ? clientName(owner) : null, isActive: row.is_active !== false, imageAssetId: row.image_asset_id as string | null ?? null, imagePath: image?.path as string | null ?? null, imageUrl: await signed(client, image), createdAt: String(row.created_at), updatedAt: String(row.updated_at), ingredients: ingredients.sort((a, b) => Number(a.ingredient_order) - Number(b.ingredient_order)).map((entry) => ({ id: String(entry.id), name: String(entry.name), quantity: entry.quantity as string | null ?? null, unit: entry.unit as string | null ?? null, notes: entry.notes as string | null ?? null, ingredientOrder: Number(entry.ingredient_order) })) };
}

export function createAdminEditorialRepository(client: SupabaseClient) {
  const clients = async (): Promise<EditorialClient[]> => { const { data, error } = await client.from("clients").select("id,profile:profiles(full_name,email,avatar_url)").order("created_at").limit(300); if (error) throw error; return (data ?? []).map((value) => { const row = value as Row; const profile = item(row.profile); return { id: String(row.id), name: clientName(row), email: profile?.email as string | null ?? null, avatarUrl: profile?.avatar_url as string | null ?? null }; }); };
  const createAsset = async (path: string, title: string, scope: string, clientId: string | null, kind: string) => { const { data, error } = await client.from("media_assets").insert({ bucket: "images", path, title, alt_text: title, asset_type: "other", scope, client_id: clientId, metadata: { kind } }).select("id").single(); if (error) throw error; return String(data.id); };
  const replaceIngredients = async (recipeId: string, ingredients: AdminRecipeIngredient[]) => { const { error: removeError } = await client.from("recipe_ingredients").delete().eq("recipe_id", recipeId); if (removeError) throw removeError; const { error } = await client.from("recipe_ingredients").insert(ingredients.map((entry, index) => ({ recipe_id: recipeId, name: entry.name, quantity: entry.quantity, unit: entry.unit, notes: entry.notes, ingredient_order: index }))); if (error) throw error; };
  return {
    clients,
    async tipCategories() { const { data, error } = await client.from("tip_categories").select("id,name").order("name").limit(200); if (error) throw error; return (data ?? []) as { id: string; name: string }[]; },
    async listTips(filters: ReturnType<typeof editorialFilters>) { const query = (head = false) => { let value = client.from("tips").select(tipSelect, { count: "exact", head }).order("created_at", { ascending: false }).order("id", { ascending: false }); if (filters.search) value = value.ilike("title", `%${filters.search}%`); if (filters.status !== "all") value = value.eq("is_active", filters.status === "active"); if (filters.scope !== "all") value = value.eq("scope", filters.scope); if (filters.categoryId) value = value.eq("category_id", filters.categoryId); if (filters.clientId) value = value.eq("client_id", filters.clientId); return value; }; const start = (filters.page - 1) * 20; const result = await readAdminPage(() => query().range(start, start + 19), () => query(true), start); return { items: await Promise.all((result.rows as Row[]).map((row) => mapTip(row, client))), total: result.total, page: filters.page, pageSize: 20 }; },
    async getTip(id: string) { const { data, error } = await client.from("tips").select(tipSelect).eq("id", id).maybeSingle(); if (error) throw error; return data ? mapTip(data as Row, client) : null; },
    async saveTip(id: string | null, input: TipInput, imageAssetId?: string | null) { const payload = { title: input.title, slug: input.slug, summary: input.summary, content: input.content, category_id: input.categoryId, scope: input.scope, client_id: input.clientId, is_active: input.isActive, ...(imageAssetId === undefined ? {} : { image_asset_id: imageAssetId }) }; if (id) { const { data, error } = await client.from("tips").update(payload).eq("id", id).select("id").single(); if (error) throw error; return String(data.id); } const { data, error } = await client.from("tips").insert(payload).select("id").single(); if (error) throw error; return String(data.id); },
    async toggleTip(id: string, active: boolean) { const { data, error } = await client.from("tips").update({ is_active: active }).eq("id", id).select("is_active").single(); if (error || data?.is_active !== active) throw error ?? new Error("Não foi possível atualizar o status da dica."); },
    async listRecipes(filters: ReturnType<typeof editorialFilters>) { const query = (head = false) => { let value = client.from("recipes").select(recipeSelect, { count: "exact", head }).order("created_at", { ascending: false }).order("id", { ascending: false }); if (filters.search) value = value.ilike("name", `%${filters.search}%`); if (filters.status !== "all") value = value.eq("is_active", filters.status === "active"); if (filters.scope !== "all") value = value.eq("scope", filters.scope); if (filters.clientId) value = value.eq("client_id", filters.clientId); return value; }; const start = (filters.page - 1) * 20; const result = await readAdminPage(() => query().range(start, start + 19), () => query(true), start); return { items: await Promise.all((result.rows as Row[]).map((row) => mapRecipe(row, client))), total: result.total, page: filters.page, pageSize: 20 }; },
    async getRecipe(id: string) { const { data, error } = await client.from("recipes").select(recipeSelect).eq("id", id).maybeSingle(); if (error) throw error; return data ? mapRecipe(data as Row, client) : null; },
    async saveRecipe(id: string | null, input: RecipeInput, imageAssetId?: string | null) { const payload = { name: input.name, slug: input.slug, description: input.description, instructions: input.instructions, scope: input.scope, client_id: input.clientId, is_active: input.isActive, ...(imageAssetId === undefined ? {} : { image_asset_id: imageAssetId }) }; let recipeId = id; if (recipeId) { const { error } = await client.from("recipes").update(payload).eq("id", recipeId); if (error) throw error; } else { const { data, error } = await client.from("recipes").insert(payload).select("id").single(); if (error) throw error; recipeId = String(data.id); } await replaceIngredients(recipeId, input.ingredients); return recipeId; },
    async toggleRecipe(id: string, active: boolean) { const { data, error } = await client.from("recipes").update({ is_active: active }).eq("id", id).select("is_active").single(); if (error || data?.is_active !== active) throw error ?? new Error("Não foi possível atualizar o status da receita."); },
    async uploadCover(path: string, bytes: Uint8Array, contentType: string) { const { error } = await client.storage.from("images").upload(path, bytes, { contentType, upsert: false }); if (error) throw error; },
    createTipCover: (path: string, title: string, scope: string, clientId: string | null) => createAsset(path, title, scope, clientId, "tip_cover"),
    createRecipeCover: (path: string, title: string, scope: string, clientId: string | null) => createAsset(path, title, scope, clientId, "recipe_cover"),
    async removeAsset(id: string | null, path: string | null) { if (id) { const { error } = await client.from("media_assets").delete().eq("id", id); if (error) throw error; } if (path) await client.storage.from("images").remove([path]); },
  };
}
