import type { SupabaseClient } from "@supabase/supabase-js";
import type { AdminExercise } from "@/types/admin-exercise";
import type { exerciseListFilters } from "@/domain/admin-exercise";
import { readAdminPage } from "./admin-page";
type Row=Record<string,unknown>;
const select="id,name,description,instructions,muscles,equipment,level,scope,client_id,video_id,thumbnail_asset_id,is_active,created_at,updated_at,category:exercise_categories(id,name),video:videos(provider_video_id),thumbnail_asset:media_assets(bucket,path)";
const map=async(r:Row,client:SupabaseClient):Promise<AdminExercise>=>{const c=r.category as Row|null,v=r.video as Row|null,a=r.thumbnail_asset as Row|null;const signed=a?await client.storage.from(String(a.bucket)).createSignedUrl(String(a.path),900):null;return {id:String(r.id),name:String(r.name),categoryId:c?.id as string??null,category:c?.name as string??null,description:r.description as string??null,instructions:r.instructions as string??null,muscles:(r.muscles as string[])??[],equipment:r.equipment as string??null,level:r.level as string??null,scope:r.scope as AdminExercise["scope"],clientId:r.client_id as string??null,videoId:(v?.provider_video_id as string??null),thumbnailAssetId:r.thumbnail_asset_id as string??null,thumbnailUrl:signed?.data?.signedUrl??null,isActive:!!r.is_active,createdAt:String(r.created_at),updatedAt:String(r.updated_at)}};
export function createAdminExerciseRepository(client:SupabaseClient){return {
 async categories(){const {data,error}=await client.from("exercise_categories").select("id,name").order("name").limit(200);if(error)throw error;return (data??[]) as {id:string;name:string}[];},
 async list(f:ReturnType<typeof exerciseListFilters>){const q=(head=false)=>{let x=client.from("exercises").select(select,{count:"exact",head}).order("name").order("id");if(f.search)x=x.ilike("name",`%${f.search}%`);if(f.categoryId)x=x.eq("category_id",f.categoryId);if(f.level)x=x.eq("level",f.level);if(f.equipment)x=x.eq("equipment",f.equipment);if(f.status!=="all")x=x.eq("is_active",f.status==="active");return x;};const start=(f.page-1)*f.pageSize;const {rows,total}=await readAdminPage(()=>q().range(start,start+f.pageSize-1),()=>q(true),start);return {items:await Promise.all((rows as Row[]).map(x=>map(x,client))),total,page:f.page,pageSize:f.pageSize};},
 async get(id:string){const {data,error}=await client.from("exercises").select(select).eq("id",id).maybeSingle();if(error)throw error;return data?map(data as Row,client):null;},
 async uploadThumbnail(path:string,bytes:Uint8Array,contentType:string){const {error}=await client.storage.from("images").upload(path,bytes,{contentType,upsert:false});if(error)throw error;},
 async createThumbnailAsset(path:string,title:string,scope:string,clientId:string|null){const {data,error}=await client.from("media_assets").insert({bucket:"images",path,title,alt_text:title,asset_type:"other",scope,client_id:clientId,metadata:{kind:"exercise_thumbnail"}}).select("id").single();if(error)throw error;return data.id as string;},
 async removeThumbnailAsset(id:string){const {error}=await client.from("media_assets").delete().eq("id",id);if(error)throw error;},
 async removeUpload(path:string){await client.storage.from("images").remove([path]);},
 async youtubeVideo(providerVideoId:string,title:string,scope:string,clientId:string|null){let q=client.from("videos").select("id").eq("provider","youtube").eq("provider_video_id",providerVideoId).eq("scope",scope);q=clientId?q.eq("client_id",clientId):q.is("client_id",null);const found=await q.maybeSingle();if(found.error)throw found.error;if(found.data)return {id:found.data.id as string,created:false};const {data,error}=await client.from("videos").insert({provider:"youtube",provider_video_id:providerVideoId,title,scope,client_id:clientId,is_active:true}).select("id").single();if(error)throw error;return {id:data.id as string,created:true};},
 async removeVideo(id:string){const {error}=await client.from("videos").delete().eq("id",id);if(error)throw error;},
 async save(id:string|null,input:Record<string,unknown>){if(id){const {data,error}=await client.from("exercises").update(input).eq("id",id).select("id").single();if(error)throw error;return data.id as string;}const {data,error}=await client.from("exercises").insert(input).select("id").single();if(error)throw error;return data.id as string;},
 async setActive(id:string,isActive:boolean){const {data,error}=await client.from("exercises").update({is_active:isActive}).eq("id",id).select("id,is_active").single();if(error)throw error;if(!data||data.is_active!==isActive)throw new Error("Não foi possível atualizar o status do exercício.");return data.is_active as boolean;}
};}
