"use client";

import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

type Mode = "login" | "signup" | "reset";

export function AuthForm({ mode }: { mode: Mode }) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [error, setError] = useState(searchParams.get("error") ?? ""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const provider = async (name: "google" | "apple" | "facebook") => { setError(""); setBusy(true); try { const supabase = createSupabaseBrowserClient(); const { error: authError } = await supabase.auth.signInWithOAuth({ provider, options: { redirectTo: `${window.location.origin}/auth/callback` } }); if (authError) throw authError; } catch (cause) { console.error("[auth/oauth]", cause); setError("Este provedor não está configurado ou não pôde iniciar o login."); setBusy(false); } };
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setMessage(""); if (mode === "signup" && password !== confirmation) { setError("As senhas não coincidem."); return; } setBusy(true); try { const supabase = createSupabaseBrowserClient(); if (mode === "login") { const { error: authError } = await supabase.auth.signInWithPassword({ email, password }); if (authError) throw authError; router.replace("/app/inicio"); router.refresh(); } else if (mode === "signup") { const { data, error: authError } = await supabase.auth.signUp({ email, password, options: { data: { full_name: name } } }); if (authError) throw authError; if (data.session) { router.replace("/app/inicio"); router.refresh(); } else setMessage("Cadastro realizado. Verifique seu e-mail para ativar a conta."); } else { const { error: authError } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/recuperar-senha` }); if (authError) throw authError; setMessage("Se o e-mail estiver cadastrado, você receberá as instruções."); } } catch (cause) { console.error("[auth/form]", cause); setError(cause instanceof Error ? cause.message : "Não foi possível concluir a operação."); } finally { setBusy(false); } };
  return <><form className="auth-form" onSubmit={submit}>{mode === "signup" && <label>Nome<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Seu nome" /></label>}<label>E-mail<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="seu@email.com" /></label>{mode !== "reset" && <label>Senha<input required minLength={6} type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Sua senha" /></label>}{mode === "signup" && <label>Confirmar senha<input required minLength={6} type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder="Confirme sua senha" /></label>}{mode === "login" && <div className="auth-options"><a href="/esqueci-senha">Esqueceu a senha?</a></div>}<button className="button button-primary full-width" disabled={busy} type="submit">{busy ? "Aguarde..." : mode === "login" ? "Entrar" : mode === "signup" ? "Criar conta" : "Enviar instruções"}</button></form>{(error || message) && <p className={error ? "auth-feedback auth-error" : "auth-feedback auth-success"} role="alert">{error || message}</p>}{mode !== "reset" && <><div className="social-divider"><span>Ou entre com</span></div><div className="social-row">{(["google", "apple", "facebook"] as const).map((item) => <button aria-label={`Entrar com ${item}`} disabled={busy} key={item} onClick={() => provider(item)} type="button">{item === "google" ? "G" : item === "apple" ? "⌘" : "f"}</button>)}</div></>}</>;
}
